### ISSUE TITLE
docker build 的时候发生了错误.[ext-src/swoole_admin_server.lo]

### ISSUE THREAD

**Issue by gbcmikeblue** [yansongda/docker-php-fpm#1]
文件：
cp yansonda.docker-php-fpm/docker-php-fpm/7.4/bullseye/Dockerfile ../../
cd yansonda.docker-php-fpm/docker-php-fpm/7.4
命令：
docker build -t php-7.4-test .
失败：
...
#5 533.0 g++: fatal error: Killed signal terminated program cc1plus
#5 533.0 compilation terminated.
#5 533.1 make: *** [Makefile:196: ext-src/swoole_admin_server.lo] Error 1
#5 533.1 make: *** Waiting for unfinished jobs....
...
请问这个情况，大佬遇到过吗

**Comment by yansongda** [comment]
没遇到过，你自己加了其它东西吧

**Comment by gbcmikeblue** [comment]
错误解决更新！

错误：
#5 2393.1 g++: fatal error: Killed signal terminated program cc1plus
#5 2393.1 compilation terminated.
#5 2393.2 make: *** [Makefile:214: ext-src/swoole_admin_server.lo] Error 1
#5 2393.2 make: *** Waiting for unfinished jobs....


解决办法，扩大docker可使用的内存，即可build 成功。
