### ISSUE TITLE
建议博主检测一下这个镜像，这个镜像很可能里面被挂挖矿病毒了

### ISSUE THREAD

**Issue by mohaike** [yansongda/docker-php-fpm#2]
我前几天拿这个镜像搭php服务器，然后阿里云那边警告我说我的服务器被拿来挖矿了，在服务器上找了一圈，发现病毒是来自于这个镜像创建的容器的。
![image](https://user-images.githubusercontent.com/6419057/182073761-46239f2a-86a5-47c1-aaf3-5ca1224fca87.png)

**Comment by yansongda** [comment]
是不是你自己的网站有漏洞，给提权了哦

源码都是开源的，这种问题还是确认后再好好看看

PS，这镜像一直用于我这边生产环境，很稳定。你可以拉原生镜像做验证，不要拉你自己二次封装的镜像

**Comment by mohaike** [comment]
用的就是这个镜像

**Comment by yansongda** [comment]
你看你自己的 dockerfile 吧，这个镜像是 100% 没问题的。

<img width="858" alt="截屏2022-08-02 14 39 49" src="https://user-images.githubusercontent.com/11869114/182308928-9efef93b-08ae-4942-aae3-49a707b896fd.png">

**Comment by mohaike** [comment]
嗯嗯，我误会了，真的非常不好意思，因为我后来用了另外一个镜像，今天发现有人在另外一个俄罗斯的服务器那边给我下载挖矿病毒....我现在非常困惑，看起来我是开php容器，当服务器就会有病毒往我的那个容器里塞病毒，这要怎么防呢😭
